### ISSUE TITLE
NullPointerException if IndentPadding is used and a value is null

### ISSUE THREAD

**Issue by andreasvef** [billdavidson/JSONUtil#6]
java.lang.NullPointerException
    at org.kopitubruk.util.json.JSONUtil.isRecursible(JSONUtil.java:396)
    at org.kopitubruk.util.json.JSONUtil.appendObjectPropertyValue(JSONUtil.java:453)
    at org.kopitubruk.util.json.JSONUtil.appendRecursiblePropertyValue(JSONUtil.java:422)
    at org.kopitubruk.util.json.JSONUtil.appendPropertyValue(JSONUtil.java:382)

isRecursible should just return false if the value is null

**Comment by billdavidson** [comment]
isRecursible() was always meant to be protected from nulls.  I'm adding a check after the check for havePadding but before the call to isRecursible().  Padding is the exception, not the norm so I prefer not to add an additional null check to the normal case to cover the less common case.  The less common case will instead get its own null check.

A test for this is also being added to the JUnit tests.  It should have been there already.

The fix is in the trunk, java7, java6 and java5 branches and will be in the next release.

Thank you for submitting this bug report.  Just curious, what type of application are you using this library for?  Given the reports you've submitted, it would seem that you use it heavily.
